name: Enhancement
description: New feature or improvement
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to accomplish?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
